version: '3'

services:

  frontend:
      build:
        context: ./frontend
      ports:
            - "3000:3000"
      volumes: 
          - ./app   
      stdin_open: true
      command: yarn start
      restart: always
  backend:
      build: ./backend
      command: bash -c "python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000"
      volumes: 
        - .:/code
      ports: 
        - "8000:8000" 
      depends_on: 
        - db-mongo   

  db-mongo:
        image: mongo
        container_name: mongodb
        restart: always
        ports: 
          - 27017:27017
        environment: 
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        

  db-mongo-express:
        image: mongo-express
        restart: always
        ports: 
          - 8081:8081
        environment: 
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
          ME_CONFIG_MONGODB_SERVER: db-mongo
        restart: unless-stopped  
          
        
